# Tasks Plugin for Fabrikator
# In-memory task management for agent sessions

plugin:
  name: Task Manager
  slug: tasks
  author: Fabrikator Team
  description: |
    Manage a list of tasks for the current session.
    Allows agents to create, update, and track their progress on tasks.
  tags:
    - tasks
    - planning
    - memory
    - state
  iconUrl: https://fabrikator.ai/icons/tasks.png

requirements:
  environment: []

capabilities:
  dataAccess:
    sessionState: true

  ui:
    type: "proxy"
    port: 3000
    entrypoint: "/"
    slots:
      - name: "agent-session-view"
        label: "Tasks"
        icon: "assignment"

  executionDefaults:
    type: docker
    config:
      image: ghcr.io/unforkableco/forge-plugins-tasks:latest
      port: 8080

  prompts:
    agents:
      - agent: cad
        position: append
        priority: 60
        content: |
          ## TASK MANAGEMENT

          **CRITICAL:**
          Start every design session with a detailed task list that will mirror the roadmap you have in mind. This will make sure you're not forgetting anything.
          Start with planning your tasks and declaring them using the plugin.
          As you progress through the tasks, update their status to "completed".
          Always check that the tasks you declared are completed before moving on to the next task.
          
          You can manage your own task list using the `add_task`, `complete_task`, `list_tasks`, and `delete_task` tools.
          
          **When to use this:**
          - ALWAYS
          - At the start of a complex request, break it down into tasks and add them.
          - As you complete steps, update their status to "completed".
          - If you need to change your plan, add or delete tasks.
          
          **Example:**
          ```
          // Add a task
          call_plugin(pluginSlug="forge-plugins-tasks", toolName="add_task", args={ label: "Design the enclosure base" })
          
          // Complete a task
          call_plugin(pluginSlug="forge-plugins-tasks", toolName="complete_task", args={ label: "Design the enclosure base" })
          
          // Check if done
          const status = call_plugin(pluginSlug="forge-plugins-tasks", toolName="check_all_tasks_complete", args={})
          if (!status.allComplete) {
             console.log("Remaining:", status.remaining)
          }
          ```

  tools:


    - name: add_task
      description: Add a new task to a specific task list.
      parameters:
        type: object
        properties:
          label:
            type: string
            description: The label (identifier) of the task.
          labels:
            type: array
            items: {type: string}
            description: List of task labels to add at once.
        required: []
      execution:
        config:
          endpoint: /add_task
    
    - name: complete_task
      description: Mark a task as completed.
      parameters:
        type: object
        properties:
          label:
            type: string
            description: The label of the task to complete.
        required: [label]
      execution:
        config:
          endpoint: /complete_task

    - name: list_tasks
      description: List all tasks in a task list.
      parameters:
        type: object
        properties: {}
        required: []
      execution:
        config:
          endpoint: /list_tasks

    - name: delete_task
      description: Delete a task from the list.
      parameters:
        type: object
        properties:
          label:
            type: string
            description: The label of the task to delete.
        required: [label]
      execution:
        config:
          endpoint: /delete_task
    
    - name: check_all_tasks_complete
      description: Check if all tasks are completed. Returns object with status and remaining tasks.
      parameters:
        type: object
        properties: {}
        required: []
      execution:
        config:
          endpoint: /check_all_tasks_complete

pricing:
  model: free
